const apiList = [
  {
    id: 1,
    category: "API Directories",
    name: "APIs.guru",
    link: "https://apis.guru/api-doc/",
    description: "OpenAPI API directory",
  },
  {
    id: 2,
    category: "Art & Images",
    name: "Art Institute of Chicago",
    link: "https://api.artic.edu/docs/#quick-start",
    description: "Artwork from the museum",
  },
  {
    id: 3,
    category: "Art & Images",
    name: "COLOURlovers",
    link: "https://www.colourlovers.com/api",
    description: "Color trends",
  },
  {
    id: 4,
    category: "Art & Images",
    name: "DiceBear",
    link: "https://www.dicebear.com/how-to-use/http-api",
    description: "Generate random SVG avatars",
  },
  {
    id: 5,
    category: "Art & Images",
    name: "Dogs",
    link: "https://dog.ceo/dog-api/",
    description: "Random dog images",
  },
  {
    id: 6,
    category: "Art & Images",
    name: "HTTP Cats",
    link: "https://http.cat/",
    description: "Cat images for HTTP status codes",
  },
  {
    id: 7,
    category: "Art & Images",
    name: "Lorem Picsum",
    link: "https://picsum.photos/",
    description: "Placeholder images",
  },
  {
    id: 8,
    category: "Art & Images",
    name: "Metropolitan Museum of Art",
    link: "https://metmuseum.github.io/",
    description: "Artwork from the museum",
  },
  {
    id: 9,
    category: "Art & Images",
    name: "PHP-Noise",
    link: "https://php-noise.com/",
    description: "Noise background image generator",
  },
  {
    id: 10,
    category: "Art & Images",
    name: "Placebear",
    link: "https://placebear.com/",
    description: "Pictures of bears for use as placeholders",
  },
  {
    id: 11,
    category: "Art & Images",
    name: "Random Dog",
    link: "https://random.dog/",
    description: "Random dog images",
  },
  {
    id: 12,
    category: "Art & Images",
    name: "RandomFox",
    link: "https://randomfox.ca/",
    description: "Random pictures of foxes",
  },
  {
    id: 13,
    category: "Art & Images",
    name: "ReSmush",
    link: "https://resmush.it/api",
    description: "Image compression and optimization",
  },
  {
    id: 14,
    category: "Art & Images",
    name: "RoboHash",
    link: "https://robohash.org/",
    description: "Generate unique images from text",
  },
  {
    id: 15,
    category: "Art & Images",
    name: "Vadivelu Status Codes",
    link: "https://vadivelu.anoram.com/",
    description: "HTTP Codes with images",
  },
  {
    id: 16,
    category: "Calendar",
    name: "Nager.Date",
    link: "https://date.nager.at/",
    description: "Public holidays",
  },
  {
    id: 17,
    category: "Calendar",
    name: "UK Bank Holidays",
    link: "https://www.api.gov.uk/gds/bank-holidays/#bank-holidays",
    description: "UK bank holidays",
  },
  {
    id: 18,
    category: "Content",
    name: "4chan",
    link: "https://github.com/4chan/4chan-API",
    description: "4chan's read-only API",
  },
  {
    id: 19,
    category: "Content",
    name: "Anime News Network",
    link: "https://www.animenewsnetwork.com/encyclopedia/api.php",
    description: "Anime/manga encyclopedia",
  },
  {
    id: 20,
    category: "Content",
    name: "Ceska Televize",
    link: "https://www.ceskatelevize.cz/xml/tv-program/",
    description: "Czech television program data",
  },
  {
    id: 21,
    category: "Content",
    name: "Chronicling America",
    link: "https://chroniclingamerica.loc.gov/about/api/",
    description: "Historic US newspapers",
  },
  {
    id: 22,
    category: "Content",
    name: "Crossref",
    link: "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
    description: "Scholarly metadata",
  },
  {
    id: 23,
    category: "Content",
    name: "Final Space",
    link: "https://finalspaceapi.com/docs/",
    description: "Television show Final Space",
  },
  {
    id: 24,
    category: "Content",
    name: "HackerNews",
    link: "https://github.com/HackerNews/API",
    description: "Hacker News API",
  },
  {
    id: 25,
    category: "Content",
    name: "Ice and Fire",
    link: "https://anapioficeandfire.com/",
    description:
      "\n            Quantified and structured data from the universe of Ice and Fire\n          ",
  },
  {
    id: 26,
    category: "Content",
    name: "Jikan",
    link: "https://jikan.moe/",
    description: "Unofficial MyAnimeList API",
  },
  {
    id: 27,
    category: "Content",
    name: "Listly",
    link: "https://list.ly/api/docs",
    description: "Top 10 lists",
  },
  {
    id: 28,
    category: "Content",
    name: "MCU-Countdown",
    link: "https://github.com/DiljotSG/MCU-Countdown/blob/develop/docs/API.md",
    description: "When is the next MCU film?",
  },
  {
    id: 29,
    category: "Content",
    name: "Mediawiki",
    link: "https://www.mediawiki.org/wiki/API:Main_page#",
    description: "Wikipedia page content and revisions",
  },
  {
    id: 30,
    category: "Content",
    name: "Open Library",
    link: "https://openlibrary.org/developers/api",
    description: "Books and book-related data",
  },
  {
    id: 31,
    category: "Content",
    name: "Reddit",
    link: "https://www.reddit.com/dev/api/",
    description: "Public content from Reddit",
  },
  {
    id: 32,
    category: "Content",
    name: "Reddit Stocks",
    link: "https://tradestie.com/apps/reddit/api/",
    description: "Top stocks from Wallstreetbets",
  },
  {
    id: 33,
    category: "Content",
    name: "Rick and Morty",
    link: "https://rickandmortyapi.com/",
    description: "Rick and Morty characters",
  },
  {
    id: 34,
    category: "Content",
    name: "STAPI",
    link: "https://stapi.co/api-documentation",
    description: "Star Trek information",
  },
  {
    id: 35,
    category: "Content",
    name: "SWAPI",
    link: "https://swapi.dev/",
    description: "Star Wars information",
  },
  {
    id: 36,
    category: "Content",
    name: "The Rosary",
    link: "https://therosaryapi.cf/",
    description: "Rosary prayers",
  },
  {
    id: 37,
    category: "Content",
    name: "TVMaze",
    link: "http://www.tvmaze.com/api",
    description: "TV show information",
  },
  {
    id: 38,
    category: "Content",
    name: "Wolne Lektury",
    link: "https://wolnelektury.pl/api/",
    description: "Search ebooks from wolnelektury.pl",
  },
  {
    id: 39,
    category: "Content",
    name: "WordPress",
    link: "https://developer.wordpress.org/rest-api/reference/",
    description: "Posts from any public WordPress site",
  },
  {
    id: 40,
    category: "Crypto & Finance",
    name: "Binance",
    link: "https://binance-docs.github.io/apidocs/spot/en/#introduction",
    description: "24 hr crypto data",
  },
  {
    id: 41,
    category: "Crypto & Finance",
    name: "CoinBase",
    link: "https://developers.coinbase.com/api/v2#data-endpoints",
    description: "Currency codes and names",
  },
  {
    id: 42,
    category: "Crypto & Finance",
    name: "CoinCap",
    link: "https://docs.coincap.io/",
    description: "Real time cryptocurrency prices",
  },
  {
    id: 43,
    category: "Crypto & Finance",
    name: "CoinDesk",
    link: "http://www.coindesk.com/api/",
    description: "Bitcoin price index",
  },
  {
    id: 44,
    category: "Crypto & Finance",
    name: "CoinGecko",
    link: "https://www.coingecko.com/en/api/documentation",
    description: "Cryptocurrency market data",
  },
  {
    id: 45,
    category: "Crypto & Finance",
    name: "CoinLore",
    link: "https://www.coinlore.com/cryptocurrency-data-api",
    description: "Cryptocurrency market data",
  },
  {
    id: 46,
    category: "Crypto & Finance",
    name: "CoinMap",
    link: "https://coinmap.org/api/",
    description: "Crypto ATMs",
  },
  {
    id: 47,
    category: "Crypto & Finance",
    name: "Coinpaprika",
    link: "https://api.coinpaprika.com/",
    description: "Cryptocurrency data",
  },
  {
    id: 48,
    category: "Crypto & Finance",
    name: "Currency Rates",
    link: "https://github.com/fawazahmed0/currency-api",
    description: "Currency exchange rates",
  },
  {
    id: 49,
    category: "Crypto & Finance",
    name: "DEX Screener",
    link: "https://docs.dexscreener.com/api/reference",
    description: "Blockchain screener",
  },
  {
    id: 50,
    category: "Crypto & Finance",
    name: "ExchangeRate-API",
    link: "https://www.exchangerate-api.com/docs/overview",
    description: "Exchange rates",
  },
  {
    id: 51,
    category: "Crypto & Finance",
    name: "GeckoTerminal",
    link: "https://api.geckoterminal.com/docs/index.html",
    description: "Crypto data",
  },
  {
    id: 52,
    category: "Crypto & Finance",
    name: "Gemini",
    link: "https://docs.gemini.com/rest-api/",
    description: "Cryptocurrency market data",
  },
  {
    id: 53,
    category: "Crypto & Finance",
    name: "Kraken",
    link: "https://docs.kraken.com/rest/#tag/Market-Data",
    description: "Crypto data",
  },
  {
    id: 54,
    category: "Crypto & Finance",
    name: "KuCoin",
    link: "https://docs.kucoin.com/#market-data",
    description: "Crypto data",
  },
  {
    id: 55,
    category: "Crypto & Finance",
    name: "NBP Web",
    link: "http://api.nbp.pl/en.html#info",
    description: "Currency exchange rates and gold prices",
  },
  {
    id: 56,
    category: "Crypto & Finance",
    name: "Nexchange",
    link: "https://nexchange2.docs.apiary.io/",
    description: "Cryptocurrency market data",
  },
  {
    id: 57,
    category: "Crypto & Finance",
    name: "OKX",
    link: "https://www.okx.com/docs-v5/en/#overview",
    description: "Cryptocurrency market data",
  },
  {
    id: 58,
    category: "Crypto & Finance",
    name: "Razorpay IFSC",
    link: "https://github.com/razorpay/ifsc/wiki/API",
    description: "Indian Financial Systems Codes",
  },
  {
    id: 59,
    category: "Crypto & Finance",
    name: "WazirX",
    link: "https://docs.wazirx.com/#public-rest-api-for-wazirx",
    description: "Crypto data",
  },
  {
    id: 60,
    category: "Developer Tools",
    name: "Agify",
    link: "https://agify.io/",
    description: "Predict age based on a name",
  },
  {
    id: 61,
    category: "Developer Tools",
    name: "APIC Agent",
    link: "https://www.apicagent.com/docs",
    description: "Detect browser, OS, and device from user agent",
  },
  {
    id: 62,
    category: "Developer Tools",
    name: "Arul's Public APIs",
    link: "https://aruljohn.com/api/",
    description: "Get IP address",
  },
  {
    id: 63,
    category: "Developer Tools",
    name: "Cloudflare Trace",
    link: "https://github.com/fawazahmed0/cloudflare-trace-api",
    description: "Get IP address, user agent, etc",
  },
  {
    id: 64,
    category: "Developer Tools",
    name: "Digital Ocean Status",
    link: "https://status.digitalocean.com/api",
    description: "DigitalOcean status",
  },
  {
    id: 65,
    category: "Developer Tools",
    name: "FilterLists",
    link: "https://filterlists.com/api/#/",
    description: "Lists of filters used by ad blockers",
  },
  {
    id: 66,
    category: "Developer Tools",
    name: "Genderize.io",
    link: "https://genderize.io/",
    description: "Predict gender based on a name",
  },
  {
    id: 67,
    category: "Developer Tools",
    name: "Google Favicons",
    link: "https://dev.to/derlin/get-favicons-from-any-website-using-a-hidden-google-api-3p1e",
    description: "Google's unofficial favicon fetcher",
  },
  {
    id: 68,
    category: "Developer Tools",
    name: "goQR",
    link: "https://goqr.me/api/doc/",
    description: "Create and read QR codes",
  },
  {
    id: 69,
    category: "Developer Tools",
    name: "HTTPBin",
    link: "https://httpbin.org/",
    description: "Inspect user agent and headers",
  },
  {
    id: 70,
    category: "Developer Tools",
    name: "Image-Charts",
    link: "https://documentation.image-charts.com/",
    description: "Chart images",
  },
  {
    id: 71,
    category: "Developer Tools",
    name: "IP2Location",
    link: "https://www.ip2location.io/documentation",
    description: "Get public IP address",
  },
  {
    id: 72,
    category: "Developer Tools",
    name: "IPify",
    link: "https://www.ipify.org/",
    description: "Get public IP address",
  },
  {
    id: 73,
    category: "Developer Tools",
    name: "is.gd",
    link: "https://is.gd/apishorteningreference.php",
    description: "URL shortener",
  },
  {
    id: 74,
    category: "Developer Tools",
    name: "Microlink",
    link: "https://microlink.io/docs/api/getting-started/overview",
    description: "Retrieve metadata and screenshots from any URL",
  },
  {
    id: 75,
    category: "Developer Tools",
    name: "Nationalize.io",
    link: "https://nationalize.io/",
    description: "Predict nationality based on a name",
  },
  {
    id: 76,
    category: "Developer Tools",
    name: "QuickChart",
    link: "https://quickchart.io/documentation/",
    description: "Generate charts on-the-fly",
  },
  {
    id: 77,
    category: "Developer Tools",
    name: "Serialif Color",
    link: "https://color.serialif.com/",
    description: "Get colors in different formats",
  },
  {
    id: 78,
    category: "Developer Tools",
    name: "Sixdots",
    link: "https://apidoc.six-dots.app/",
    description: "Google playstore analysis",
  },
  {
    id: 79,
    category: "Developer Tools",
    name: "Un-Shorten",
    link: "https://unshorten.me/api",
    description: "Unshorten shortened URLs",
  },
  {
    id: 80,
    category: "Developer Tools",
    name: "URLhaus",
    link: "https://urlhaus-api.abuse.ch/",
    description: "Receive and submit malware URLs",
  },
  {
    id: 81,
    category: "Food & Drink",
    name: "Cocktail Database",
    link: "https://www.thecocktaildb.com/api.php",
    description: "Cocktail recipes",
  },
  {
    id: 82,
    category: "Food & Drink",
    name: "Open Brewery DB",
    link: "https://www.openbrewerydb.org/",
    description: "Breweries",
  },
  {
    id: 83,
    category: "Food & Drink",
    name: "Open Food Facts",
    link: "https://world.openfoodfacts.org/data",
    description: "Data on food products",
  },
  {
    id: 84,
    category: "Food & Drink",
    name: "Spoonacular",
    link: "https://spoonacular.com/food-api",
    description: "Comprehensive food API",
  },
  {
    id: 85,
    category: "Food & Drink",
    name: "Whisky Hunter",
    link: "https://whiskyhunter.net/api/",
    description: "Whisky auctions",
  },
  {
    id: 86,
    category: "Fun & Games",
    name: "AmiiboAPI",
    link: "https://amiiboapi.com/docs/",
    description: "Nintendo Amiibo database",
  },
  {
    id: 87,
    category: "Fun & Games",
    name: "Barter",
    link: "https://github.com/bartervg/barter.vg/wiki",
    description: "Digital game libraries, wishlists and tradables",
  },
  {
    id: 88,
    category: "Fun & Games",
    name: "Board Game Geek",
    link: "https://boardgamegeek.com/wiki/page/BGG_XML_API2",
    description: "Board games",
  },
  {
    id: 89,
    category: "Fun & Games",
    name: "CheapShark",
    link: "https://apidocs.cheapshark.com/",
    description: "Price comparison for digital games",
  },
  {
    id: 90,
    category: "Fun & Games",
    name: "Chuck Norris Jokes",
    link: "https://api.chucknorris.io/",
    description: "Chuck Norris facts",
  },
  {
    id: 91,
    category: "Fun & Games",
    name: "D&D 5th Edition",
    link: "http://www.dnd5eapi.co/",
    description: "Official 5th Edition of Dungeons & Dragons",
  },
  {
    id: 92,
    category: "Fun & Games",
    name: "Data Dragon",
    link: "https://riot-api-libraries.readthedocs.io/en/latest/ddragon.html",
    description: "League of Legends champions API",
  },
  {
    id: 93,
    category: "Fun & Games",
    name: "Deck of Cards",
    link: "https://deckofcardsapi.com/",
    description: "Simulate a deck of cards",
  },
  {
    id: 94,
    category: "Fun & Games",
    name: "Evil Insult Generator",
    link: "https://evilinsult.com/api/",
    description: "Generate insults",
  },
  {
    id: 95,
    category: "Fun & Games",
    name: "FreeToGame",
    link: "https://www.freetogame.com/api-doc",
    description: "Free-to-play games",
  },
  {
    id: 96,
    category: "Fun & Games",
    name: "Gamerpower",
    link: "https://www.gamerpower.com/api-read",
    description: "Free games and giveaways",
  },
  {
    id: 97,
    category: "Fun & Games",
    name: "Hyrule Compendium",
    link: "https://github.com/gadhagod/Hyrule-Compendium-API",
    description: "The Legend of Zelda: BOTW",
  },
  {
    id: 98,
    category: "Fun & Games",
    name: "icanhazdadjoke",
    link: "https://icanhazdadjoke.com/api",
    description: "Dad jokes",
  },
  {
    id: 99,
    category: "Fun & Games",
    name: "Imgflip",
    link: "https://imgflip.com/api",
    description: "Popular memes",
  },
  {
    id: 100,
    category: "Fun & Games",
    name: "isEven",
    link: "https://isevenapi.xyz/",
    description: "Check if a number is even",
  },
  {
    id: 101,
    category: "Fun & Games",
    name: "JokeAPI",
    link: "https://sv443.net/jokeapi/v2/",
    description: "Jokes",
  },
  {
    id: 102,
    category: "Fun & Games",
    name: "Magic: The Gathering",
    link: "https://docs.magicthegathering.io/",
    description: "Cards and sets from MTG",
  },
  {
    id: 103,
    category: "Fun & Games",
    name: "Official Joke",
    link: "https://github.com/15Dkatz/official_joke_api",
    description: "Jokes",
  },
  {
    id: 104,
    category: "Fun & Games",
    name: "Open Trivia DB",
    link: "https://opentdb.com/api_config.php",
    description: "Trivia questions",
  },
  {
    id: 105,
    category: "Fun & Games",
    name: "PokéAPI",
    link: "https://pokeapi.co/",
    description: "Pokémon data",
  },
  {
    id: 106,
    category: "Fun & Games",
    name: "Pokémon TCG",
    link: "https://docs.pokemontcg.io/",
    description: "Pokémon card data",
  },
  {
    id: 107,
    category: "Fun & Games",
    name: "RuneScape",
    link: "https://runescape.wiki/w/Application_programming_interface",
    description: "Runescape data",
  },
  {
    id: 108,
    category: "Fun & Games",
    name: "Scryfall",
    link: "https://scryfall.com/docs/api",
    description: "Magic: The Gathering card data",
  },
  {
    id: 109,
    category: "Fun & Games",
    name: "TCGdex",
    link: "https://tcgdex.dev/",
    description: "Pokémon card data",
  },
  {
    id: 110,
    category: "Fun & Games",
    name: "XIVAPI",
    link: "https://xivapi.com/docs",
    description: "Final Fantasy XIV",
  },
  {
    id: 111,
    category: "Fun & Games",
    name: "xkcd",
    link: "https://xkcd.com/json.html",
    description: "xkcd comics",
  },
  {
    id: 112,
    category: "Fun & Games",
    name: "Yes or No?",
    link: "https://yesno.wtf/",
    description: "Randomly generate a yes or no image",
  },
  {
    id: 113,
    category: "Geo",
    name: "Adresse",
    link: "https://adresse.data.gouv.fr/api-doc",
    description: "French addresses and geocoding",
  },
  {
    id: 114,
    category: "Geo",
    name: "Country.is",
    link: "http://country.is/",
    description: "Lookup country by IP address",
  },
  {
    id: 115,
    category: "Geo",
    name: "Geocode",
    link: "https://geocode.xyz/api",
    description: "Forward/reverse geocoding",
  },
  {
    id: 116,
    category: "Geo",
    name: "GeoJS",
    link: "https://www.geojs.io/docs/v1/endpoints/",
    description: "Geolocation by IP address",
  },
  {
    id: 117,
    category: "Geo",
    name: "geoPlugin",
    link: "https://www.geoplugin.com/",
    description: "Currency conversion and geolocation data",
  },
  {
    id: 118,
    category: "Geo",
    name: "GetTheData",
    link: "https://www.getthedata.com/bng2latlong",
    description: "UK geo coordinates conversion",
  },
  {
    id: 119,
    category: "Geo",
    name: "HelloSalut",
    link: "https://hellosalut.stefanbohacek.dev/hello/",
    description: 'Translate "hello" by IP address',
  },
  {
    id: 120,
    category: "Geo",
    name: "Hong Kong GeoData Store",
    link: "https://geodata.gov.hk/gs/",
    description: "Hong Kong geo data",
  },
  {
    id: 121,
    category: "Geo",
    name: "ipapi",
    link: "https://ipapi.co/api/#introduction",
    description: "Geolocation by IP address",
  },
  {
    id: 122,
    category: "Geo",
    name: "IPGeo",
    link: "https://api.techniknews.net/",
    description: "Geolocation by IP address",
  },
  {
    id: 123,
    category: "Geo",
    name: "Nominatum",
    link: "https://nominatim.org/release-docs/latest/api/Overview/",
    description: "Locations and addresses",
  },
  {
    id: 124,
    category: "Geo",
    name: "Open Topo Data",
    link: "https://www.opentopodata.org/#public-api",
    description: "Determine elevation for lat/long",
  },
  {
    id: 125,
    category: "Geo",
    name: "Postcodes",
    link: "https://postcodes.io/",
    description: "UK geo data by postcode",
  },
  {
    id: 126,
    category: "Geo",
    name: "ViaCEP",
    link: "https://viacep.com.br/",
    description: "Brazil's postal address codes (CEPs)",
  },
  {
    id: 127,
    category: "Geo",
    name: "Zippopotamus",
    link: "http://www.zippopotam.us/",
    description: "Zip code information for 60 countries",
  },
  {
    id: 128,
    category: "Geo",
    name: "Ziptastic",
    link: "https://ziptasticapi.com/",
    description: "US geo data by zipcode",
  },
  {
    id: 129,
    category: "Government",
    name: "Banco Central Do Brasil",
    link: "https://dadosabertos.bcb.gov.br/",
    description: "Brazil Central Bank data",
  },
  {
    id: 130,
    category: "Government",
    name: "Belgian Open Data Initiative",
    link: "https://data.gov.be/en/search/datasets",
    description: "Belgian government open data",
  },
  {
    id: 131,
    category: "Government",
    name: "Brasil",
    link: "https://brasilapi.com.br/docs",
    description: "Brazil public data",
  },
  {
    id: 132,
    category: "Government",
    name: "CiviX",
    link: "https://www.bclaws.gov.bc.ca/civix/template/complete/api/index.html",
    description: "Law and bylaw content of British Columbia",
  },
  {
    id: 133,
    category: "Government",
    name: "Colorado Information Marketplace",
    link: "https://data.colorado.gov/browse",
    description: "Colorado state open data",
  },
  {
    id: 134,
    category: "Government",
    name: "Data USA",
    link: "https://datausa.io/about/api/",
    description: "US public data",
  },
  {
    id: 135,
    category: "Government",
    name: "Data.gov",
    link: "https://data.gov/",
    description: "U.S. government open data",
  },
  {
    id: 136,
    category: "Government",
    name: "Data.gov.au",
    link: "http://data.gov.au/",
    description: "Australian government open data",
  },
  {
    id: 137,
    category: "Government",
    name: "Dawum",
    link: "https://dawum.de/API/",
    description: "German election polls",
  },
  {
    id: 138,
    category: "Government",
    name: "European Commission Taxation and Customs",
    link: "https://commission.europa.eu/index_en",
    description: "Europan Comission taxes",
  },
  {
    id: 139,
    category: "Government",
    name: "FBI Wanted",
    link: "https://www.fbi.gov/wanted/api",
    description: "FBI Wanted data",
  },
  {
    id: 140,
    category: "Government",
    name: "Federal Register",
    link: "https://www.federalregister.gov/reader-aids/developer-resources/rest-api",
    description: "Daily journal of the US government",
  },
  {
    id: 141,
    category: "Government",
    name: "Food Standards Agency",
    link: "https://ratings.food.gov.uk/open-data/en-GB",
    description: "UK restaurant hygiene ratings",
  },
  {
    id: 142,
    category: "Government",
    name: "NYC Open Data",
    link: "https://opendata.cityofnewyork.us/how-to/#apidocumentation",
    description: "New York City open data",
  },
  {
    id: 143,
    category: "Government",
    name: "Open Data DC",
    link: "https://opendata.dc.gov/pages/using-apis",
    description: "Washington DC open data",
  },
  {
    id: 144,
    category: "Government",
    name: "Open Government, Canada",
    link: "https://search.open.canada.ca/opendata/",
    description: "Canadian government open data",
  },
  {
    id: 145,
    category: "Government",
    name: "Represent Civic Information",
    link: "https://represent.opennorth.ca/api/",
    description: "Canada's elected officials and electoral districts",
  },
  {
    id: 146,
    category: "Government",
    name: "USAspending",
    link: "https://api.usaspending.gov/",
    description: "U.S. federal government spending data",
  },
  {
    id: 147,
    category: "Government",
    name: "USPTO",
    link: "https://developer.uspto.gov/api-catalog",
    description: "US Patent and Trademark Office",
  },
  {
    id: 148,
    category: "Government",
    name: "World Bank",
    link: "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589",
    description: "World Bank open data",
  },
  {
    id: 149,
    category: "Health",
    name: "HealthCare.gov",
    link: "https://www.healthcare.gov/developers/",
    description: "US health insurance data",
  },
  {
    id: 150,
    category: "Health",
    name: "Makeup",
    link: "http://makeup-api.herokuapp.com/",
    description: "Makeup brands and product info",
  },
  {
    id: 151,
    category: "Health",
    name: "NPPES",
    link: "https://npiregistry.cms.hhs.gov/api-page",
    description: "US health care providers",
  },
  {
    id: 152,
    category: "Health",
    name: "openFDA",
    link: "https://open.fda.gov/",
    description: "Food & Drug Administration data (US)",
  },
  {
    id: 153,
    category: "Inspiration",
    name: "Advice Slip",
    link: "https://api.adviceslip.com/",
    description: "Generate random advice",
  },
  {
    id: 154,
    category: "Inspiration",
    name: "Affirmations",
    link: "https://www.affirmations.dev/",
    description: "Generate affirmations",
  },
  {
    id: 155,
    category: "Inspiration",
    name: "Breaking Bad Quotes",
    link: "https://github.com/shevabam/breaking-bad-quotes",
    description: "Retrieve some quotes of Breaking Bad",
  },
  {
    id: 156,
    category: "Inspiration",
    name: "Dictum",
    link: "https://github.com/fisenkodv/dictum",
    description: "Inspiring expressions",
  },
  {
    id: 157,
    category: "Inspiration",
    name: "Game of Thrones Quotes",
    link: "https://gameofthronesquotes.xyz/",
    description: "Retrieve some quotes of Game of Thrones",
  },
  {
    id: 158,
    category: "Inspiration",
    name: "Kanye",
    link: "https://kanye.rest/",
    description: "Kanye quotes",
  },
  {
    id: 159,
    category: "Inspiration",
    name: "Quotable",
    link: "https://github.com/lukePeavey/quotable",
    description: "Random quotes",
  },
  {
    id: 160,
    category: "Inspiration",
    name: "Quote Garden",
    link: "https://pprathameshmore.github.io/QuoteGarden/",
    description: "Database of 75000 quotes",
  },
  {
    id: 161,
    category: "Inspiration",
    name: "Quotes on Design",
    link: "https://quotesondesign.com/api/",
    description: "Quotes about design",
  },
  {
    id: 162,
    category: "Inspiration",
    name: "Ron Swanson Quotes",
    link: "https://github.com/jamesseanwright/ron-swanson-quotes#ron-swanson-quotes-api",
    description: "Ron Swanson quotes API",
  },
  {
    id: 163,
    category: "Jobs",
    name: "Jobicy",
    link: "https://jobicy.com/jobs-rss-feed",
    description: "List of remote jobs",
  },
  {
    id: 164,
    category: "Language",
    name: "Chinese Character Web",
    link: "http://ccdb.hemiola.com/",
    description: "Information about Chinese characters",
  },
  {
    id: 165,
    category: "Language",
    name: "Chinese Text Project",
    link: "https://ctext.org/tools/api",
    description: "Digital library for pre-modern Chinese texts",
  },
  {
    id: 166,
    category: "Language",
    name: "Datamuse",
    link: "https://www.datamuse.com/api/",
    description: "Query words matching conditions",
  },
  {
    id: 167,
    category: "Language",
    name: "Free Dictionary",
    link: "https://dictionaryapi.dev/",
    description: "Word definitions and phonetics",
  },
  {
    id: 168,
    category: "Language",
    name: "PurgoMalum",
    link: "http://www.purgomalum.com/",
    description: "Check content for profanity",
  },
  {
    id: 169,
    category: "Music",
    name: "Binary Jazz",
    link: "https://binaryjazz.us/genrenator-api/",
    description: "Fetch a random genre",
  },
  {
    id: 170,
    category: "Music",
    name: "iTunes Search",
    link: "https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/",
    description: "iTunes content",
  },
  {
    id: 171,
    category: "Music",
    name: "MusicBrainz",
    link: "https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2",
    description: "Music data",
  },
  {
    id: 172,
    category: "Music",
    name: "Openwhyd",
    link: "https://openwhyd.github.io/openwhyd/API",
    description: "Playlists from various streaming platforms",
  },
  {
    id: 173,
    category: "Open Data",
    name: "Archive.org",
    link: "https://archive.readme.io/docs",
    description: "Large public digital archive",
  },
  {
    id: 174,
    category: "Open Data",
    name: "Carbon Intensity",
    link: "https://carbon-intensity.github.io/api-definitions/",
    description: "Carbon intensity of the electricity system in Great Britain",
  },
  {
    id: 175,
    category: "Open Data",
    name: "Data.Police.UK",
    link: "https://data.police.uk/docs/",
    description: "UK crime & police data",
  },
  {
    id: 176,
    category: "Open Data",
    name: "Fipe",
    link: "https://deividfortuna.github.io/fipe/",
    description: "Brazilian vehicles and prices",
  },
  {
    id: 177,
    category: "Open Data",
    name: "House Stock Watcher",
    link: "https://housestockwatcher.com/api",
    description: "US Congress members' stock transactions",
  },
  {
    id: 178,
    category: "Open Data",
    name: "Leadsbox",
    link: "https://leadsbox.biz/",
    description: "71 Million business records in 202 countries",
  },
  {
    id: 179,
    category: "Open Data",
    name: "Open Library",
    link: "https://openlibrary.org/developers/api",
    description: "Information about books",
  },
  {
    id: 180,
    category: "Open Data",
    name: "PM2.5",
    link: "https://pm25.lass-net.org/#apis",
    description: "PM2.5 environmental data monitoring",
  },
  {
    id: 181,
    category: "Open Data",
    name: "Universities List",
    link: "https://github.com/Hipo/university-domains-list",
    description: "Universities",
  },
  {
    id: 182,
    category: "Open Data",
    name: "Vehicles",
    link: "https://vpic.nhtsa.dot.gov/api/",
    description:
      "\n            National Highway Traffic Safety Administration's catalog of vehicles\n            specs\n          ",
  },
  {
    id: 183,
    category: "Open Data",
    name: "Wayback Machine",
    link: "https://archive.org/help/wayback_api.php",
    description: "Internet archive availability",
  },
  {
    id: 184,
    category: "Open Data",
    name: "Wikipedia",
    link: "https://wikitech.wikimedia.org/wiki/Analytics/AQS/Pageviews",
    description: "Pageview stats",
  },
  {
    id: 185,
    category: "Science",
    name: "Arcsecond",
    link: "https://api.arcsecond.io/",
    description: "Worldwide astronomy data",
  },
  {
    id: 186,
    category: "Science",
    name: "arXiv",
    link: "https://info.arxiv.org/help/api/index.html",
    description: "Research-sharing platform",
  },
  {
    id: 187,
    category: "Science",
    name: "Asterank",
    link: "https://www.asterank.com/api",
    description: "Asteroids, minor planets, and other objects",
  },
  {
    id: 188,
    category: "Science",
    name: "Cat-Facts",
    link: "https://alexwohlbruck.github.io/cat-facts/docs/",
    description: "Daily cat facts",
  },
  {
    id: 189,
    category: "Science",
    name: "CelesTrak",
    link: "https://celestrak.org/NORAD/documentation/gp-data-formats.php",
    description: "General perturbations orbital data",
  },
  {
    id: 190,
    category: "Science",
    name: "GBIF",
    link: "https://www.gbif.org/developer/summary",
    description: "Global Biodiversity Information Facility",
  },
  {
    id: 191,
    category: "Science",
    name: "iDigBio",
    link: "https://github.com/idigbio/idigbio-search-api/wiki",
    description: "Digitized data for millions of biological specimens",
  },
  {
    id: 192,
    category: "Science",
    name: "ITIS",
    link: "https://www.itis.gov/ws_description.html",
    description: "Integrated Taxonomic Information System",
  },
  {
    id: 193,
    category: "Science",
    name: "NASA",
    link: "https://api.nasa.gov/",
    description: "National Aeronautics and Space Administration",
  },
  {
    id: 194,
    category: "Science",
    name: "Newton",
    link: "https://github.com/aunyks/newton-api",
    description: "Advanced math",
  },
  {
    id: 195,
    category: "Science",
    name: "Numbers",
    link: "http://numbersapi.com/#random/math",
    description: "Facts about numbers",
  },
  {
    id: 196,
    category: "Science",
    name: "Open Notify",
    link: "http://open-notify.org/Open-Notify-API/",
    description: "ISS location and people in space",
  },
  {
    id: 197,
    category: "Science",
    name: "Spaceflight News",
    link: "https://api.spaceflightnewsapi.net/documentation",
    description: "Spaceflight related news",
  },
  {
    id: 198,
    category: "Science",
    name: "SpaceX",
    link: "https://github.com/r-spacex/SpaceX-API",
    description: "Launch and rocket data",
  },
  {
    id: 199,
    category: "Science",
    name: "SunriseSunset",
    link: "https://sunrisesunset.io/api/",
    description: "Sunrise and sunset times",
  },
  {
    id: 200,
    category: "Science",
    name: "TheSpaceDevs",
    link: "https://thespacedevs.com/llapi",
    description: "Rocket launches, space events and crewed spaceflight",
  },
  {
    id: 201,
    category: "Science",
    name: "USGS Earthquake Catalog",
    link: "https://earthquake.usgs.gov/fdsnws/event/1/",
    description: "Latest earthquakes",
  },
  {
    id: 202,
    category: "Sports",
    name: "CityBikes",
    link: "http://api.citybik.es/v2/",
    description: "Bike sharing networks",
  },
  {
    id: 203,
    category: "Sports",
    name: "Ergast F1",
    link: "http://ergast.com/mrd/",
    description: "Motor racing data",
  },
  {
    id: 204,
    category: "Sports",
    name: "Football-Data",
    link: "https://www.football-data.org/documentation/quickstart",
    description: "Football (soccer) competitions and data",
  },
  {
    id: 205,
    category: "Sports",
    name: "nhlapi",
    link: "https://gitlab.com/dword4/nhlapi",
    description: "NHL data",
  },
  {
    id: 206,
    category: "Test Data",
    name: "Bacon Ipsum",
    link: "https://baconipsum.com/json-api/",
    description: "Generate fake data for testing",
  },
  {
    id: 207,
    category: "Test Data",
    name: "Faker",
    link: "https://fakerapi.it/en",
    description: "Generate fake data",
  },
  {
    id: 208,
    category: "Test Data",
    name: "JSONPlaceholder",
    link: "http://jsonplaceholder.typicode.com/guide/",
    description: "Fake REST API for testing",
  },
  {
    id: 209,
    category: "Test Data",
    name: "Loripsum",
    link: "https://loripsum.net/",
    description: "Generate fake placeholder text",
  },
  {
    id: 210,
    category: "Test Data",
    name: "RandomUser",
    link: "https://randomuser.me/",
    description: "Fake user data generator",
  },
  {
    id: 211,
    category: "Test Data",
    name: "Reqres",
    link: "https://reqres.in/",
    description: "Test against a real API",
  },
  {
    id: 212,
    category: "Test Data",
    name: "REST",
    link: "https://restful-api.dev/",
    description: "Rest API for testing",
  },
  {
    id: 213,
    category: "Test Data",
    name: "Softwium",
    link: "https://softwium.com/fake-api/",
    description: "Dummy JSON data for a variety of categories",
  },
  {
    id: 214,
    category: "Test Data",
    name: "UUID Generator",
    link: "https://www.uuidtools.com/docs",
    description: "Generate UUIDs and GUIDs",
  },
  {
    id: 215,
    category: "Transportation",
    name: "Derhuerst",
    link: "https://github.com/derhuerst/vbb-rest/blob/6/docs/readme.md",
    description: "Public transport for Berlin & Brandenburg",
  },
  {
    id: 216,
    category: "Transportation",
    name: "iRail",
    link: "https://docs.irail.be/",
    description: "Belgian railways",
  },
  {
    id: 217,
    category: "Transportation",
    name: "MBTA",
    link: "https://www.mbta.com/developers/v3-api",
    description: "Public transport for Boston",
  },
  {
    id: 218,
    category: "Transportation",
    name: "Metro Lisboa",
    link: "https://metrolisboa.pt/",
    description: "Subway line status",
  },
  {
    id: 219,
    category: "Weather",
    name: "7Timer!",
    link: "http://www.7timer.info/doc.php?lang=en",
    description: "Weather forecasts for astronomy",
  },
  {
    id: 220,
    category: "Weather",
    name: "Aviation Weather Center",
    link: "https://aviationweather.gov/data/api/",
    description: "Aviation Digital Data Service (ADDS) data",
  },
  {
    id: 221,
    category: "Weather",
    name: "Open-Meteo",
    link: "https://open-meteo.com/en/docs",
    description: "Open source weather API",
  },
  {
    id: 222,
    category: "Weather",
    name: "openSenseMap",
    link: "https://docs.opensensemap.org/",
    description: "Personal senseBox (weather station) data",
  },
  {
    id: 223,
    category: "Weather",
    name: "SG Weather",
    link: "https://data.gov.sg/dataset/realtime-weather-readings",
    description: "Realtime weather readings for Singapore",
  },
  {
    id: 224,
    category: "Weather",
    name: "wttr",
    link: "https://github.com/chubin/wttr.in",
    description: "Console-oriented weather forecast service",
  },
];

export { apiList };
