const appCategories = [
  "Social Networking",
  "Entertainment",
  "Education",
  "Health and Fitness",
  "Lifestyle",
  "News",
  "Shopping",
  "Sports",
  "Travel",
  "Finance",
  "Business",
  "Music",
  "Photography",
  "Productivity",
  "Games",
  "Books",
  "Food and Drink",
  "Weather",
  "Medical",
  "Navigation",
  "Kids",
  "Graphics and Design",
  "Developer Tools",
  "Reference",
  "Utilities",
];

export { appCategories };
